window.ETAPPENINFO = {
   "Etappe1.gpx": {
      "Etappennummer": "Etappe1.gpx.gpx",
      "Titel": "Transalp-Etappe 1: Innsbruck - Bozen",
      "Kurztext": "Die erste Etappe der Transalp führt von der Innenstadt Innsbrucks über den Brennerpass nach Sterzing. Von dort geht es auf das 2211m hohe Penser Joch und abschließend die 50km lange Abfahrt in die Hauptstadt Südtirols Bozen. Besondere Highlights dieser Etappe sind die Befahrung des Penser Jochs von Norden und die anschließende über 50 km lange Abfahrt durch das Sarntal und die tunnelreiche Schlucht im unteren Teil hinunter nach Bozen.",
      "Streckenbeschreibung": "Start im Ortszentrum von Innsbruck bei der Innbrücke am Universitätshauptgebäude. Wer mit dem Auto anreist hat die Möglichkeit auf dem öffentlichen Parkplatz an der Universität zu parken (ca. 200 Meter von der Innbrücke entfernt). Von der Innbrücke ausgehend geht man geradeaus Richtung Matrei zur Hauptstraße, dort biegt man bei der großen Hinweistafel Matrei am Brenner ab und fährt Richtung Matrei am Brenner weiter an der Skisprungschanze vorbei. Man folgt der B182 bis zur italienischen Grenze am Brennerpass, wo zahlreiche Restaurants und Bars zu einer ersten Pause einladen. Bald darauf der Beschilderung „Sterzing - Vipiteno“ folgen. Angekommen in Sterzing folgt man im Kreisverkehr der Beschilderung Passo Pennes - Penser Joch. Nun auf der SS508 Richtung Penser Joch geht es mäßig steil aufwärts. Oben angekommen, ist ein Stopp also schon fast so etwas wie eine Pflicht, denn die Aussicht auf die umliegende Bergwelt ist überwältigend. Danach darf man sich auf eine sehr lange Abfahrt mit schönen Panoramen freuen. Bis nach Bozen sind es knapp 50 Kilometer, die ersten Kilometer sind mit einem Gefälle von bis zu 12 Prozent recht steil, bis auf drei Spitzkehren gleich am Anfang ist die Strecke aber wenig kurvig. Nach den ersten Kilometern wird der Weg deutlich flacher und man kann dann auch wieder die Hände getrost von der Bremse nehmen und die schöne Aussicht ausgiebig genießen. Bis zum Ortsschild Bozen der Südtiroler Strasse folgen und anschließend in die Via Dr. Julius Perathoner abbiegen und bis zum Stadtzetrum fahren. Dort gibt es einige Aufenthaltsmöglichkeiten um sich für die 2. Etappe zu stärken und zu übernachten.",
      "Ausgangspunkt": "Innsbruck",
      "Endpunkt": "Bozen",
      "auf": 3472,
      "ab": 3777,
      "maxHoehe": 2213,
      "Schwierigkeitsgrad": "mittelschwierig",
      "Laenge": "120",
      "Zeit": "6",
      "Pässe": "Brennerpass, Penser Joch",
      
   },
   "Etappe2.gpx": {
      "Etappennummer": "Etappe2.gpx.gpx",
      "Titel": "Transalp-Etappe 2: Bozen - Bormio",
      "Kurztext": "Diese Etappe führt ausgehend vom Stadtzetrum Bozens über Meran und das Vinschgau nach Bormio. Highlight dieser Etappe ist das Erklimmen des berühmten Stilfser Jochs, einem der höchsten Bergpässe Europas.",
      "Streckenbeschreibung": "Von der Stadtmitte Bozens fährt man über den Radweg entlang der Eisack Richtung Meran und überwindet dort lediglich 100 Höhenmeter. Angekommen in Meran biegt man auf den Radweg in Richtung Vinschgau ab und folgt diesem Radweg entlang der Etsch bis nach Latsch. In Latsch angekommen biegt man in die SS41 ab in Richtung Münstertal. Dieser Strasse folgt man bis nach Santa Maria Val Müstair in der Schweiz. Dort biegt man ab in die 559 Richtung Umbrailpass. Oben angekommen ist man allerdings noch nicht ganz oben. Nach einer kurzen Abfahrt färht man über die Grenze zurück nach Südtirol. Dort folgt man der SS38 weiter geradeaus in Richtung Stilfser Joch. Dieser Strasse folgt man 3,2 Kilometer bis man oben angekommen ist. Oben angekommen laden einige Gaststätten auf der Passhöhe zu einer letzten Einkehr vor der langen Abfahrt nach Bormio, dem Ziel dieser Etappe. Oben am Stilfser Joch sollte man sich unbedingt die andere Seite der Passstrasse ansehen, die mit ihrer sehr kurvenreichen Auffahrt begeistert. Die Aussicht auf den Nationalpark Stilfser Joch sollte man sich auch anschauen. Nach dieser Einkehr macht man sich auf den Weg über die SS38 in Richtung Bormio. Dieses mal biegt man links ab in Richtung Bormio anstatt weiter Richtung Umbrail zu fahren. Es gilt höchste Konzentration in der sehr kurvenreichen Abfahrt in Richtung Bormio. In Bormio angekommen folgt man der Strada Statale dello Stelvio bis zur Via San Sebastiano und biegt dort rechts ab in Richtung Ortszentrum und hier endet die 2. Etappe und somit dem längsten und anspruchsvollsten Abschnitt der Transalp. In Bormio gibt es einige Übernachtungsmöglichkeiten und Einkehrmöglichkeiten zur Vorbereiten des dritten Abschnitts dieser Transalp.",
      "Ausgangspunkt": "Bozen",
      "Endpunkt": "Bormio",
      "auf": 3132,
      "ab": 2197,
      "maxHoehe": 2757,
      "Schwierigkeitsgrad": "mittelschwierig",
      "Laenge": "138",
      "Zeit": "7",
      "Pässe": "Stilfser Joch",
      
   },
   "Etappe3.gpx": {
      "Etappennummer": "Etappe3.gpx.gpx",
      "Titel": "Transalp-Etappe 3: Bormio - Cles",
      "Kurztext": "Die dritte Etappe der Transalp führt von Bormio ins Städtchen Cles. Vom Skiort Bormio führt dieser Abschnitt in RichtungGaviapass. Von dort geht es stetig hoch auf den 2618m hohen Gaviapass. Anschließend geht es länger Bergab in Richtung Ponte di Legno, wo es dann weiter zum Passo del Tonale geht. Nach diesem Pass geht es dann weiter abwärts in Richtung Tagesziel Cles.",
      "Streckenbeschreibung": "Im Stadtzentrum von Bormio nimmt man die SP29 und von dort aus geht es stetig bergauf bis zum Gaviapass. In einer kurvenreichen Strasse kämpft man sich Höhenmeter um Höhenmeter höher bis zum 2612m hoch gelegenen Gaviapass. Die mittlerweile beidseitig asphaltierte Straße ist schmal und wenig befahren. Zu Unrecht fristet der Gaviapass ein recht unbemerktes Leben im Schatten des Stilfserjochs, denn landschaftlich ist er wesentlich eindrucksvoller, wenn auch baulich nicht so spektakulär. Das macht er jedoch durch seinen hohen Abwechslungsreichtum wett. An der Passhöhe liegt der Lago Bianco vor den schneebedeckten Spitzen des Corno dei Tre Signori (3359 m). Noch schöner: der Lago Nero (2386 m) kurz unterhalb der Passhöhe aus südlicher Richtung. Der Gaviapass ist nach unserer Meinung einer der absolut schönsten Pässe der Alpen. Vom Gaviapass aus geht es nun eine 18km lange Abfahrt in Richtung Ponte die Legno, bevor es über die SS42 12km hoch zum Passo del Tonale geht, welcher die Orte Ponte di Legno und Fucine verbindet. Man durchquert auf dieser Strasse auch das Skigebiet Val di Sole. Angekommen auf dem Passo del Tonale, welcher mit 626 Höhenmeter und 12,6km weitaus weniger anstrengend ist als der bereits zurückgelegene Gaviapass, fährt man abwärts bis nach Fucine. Die Etappe endet mit einem lockeren Ausrollen in Richtung Cles, wo die 3. Etappe endet. In dieser Stadt findet man auch einige Übernachtungsmögligkeiten um am nächsten Tag die letzte Etappe in Richtung Gardasee in Angriff zu nehmen.",
      "Ausgangspunkt": "Bormio",
      "Endpunkt": "Cles",
      "auf": 2547,
      "ab": 3197,
      "maxHoehe": 2621,
      "Schwierigkeitsgrad": "mittelschwierig",
      "Laenge": "105",
      "Zeit": "5",
      "Einkehr": "Gaviapass, Passo del Tonale",
     
   },
   "Etappe4.gpx": {
      "Etappennummer": "Etappe4.gpx.gpx",
      "Titel": "Transalp-Etappe 4: Cles –  Riva del Garda",
      "Kurztext": "Die letzte Etappe der Transalp führt von Cles in einem stetigen Auf und Ab nach Riva del Garda, dem Endpunkt der Transalp. Angekommen in Riva del Garda läd der Gardasee zum wohlverdienten Baden im Gardasee ein.",
      "Streckenbeschreibung": "Startpunkt der Etappe ist die kleine Stadt Cles. Von dort aus folgt man der SS43 bis nach Rocchetta. Dort biegt man ab auf die SS241 und folgt dieser bis zum 1019m hoch gelegenen Lago di Andalo. Vom Lago di Andalo aus führt eine Abfahrt, am Lago di Molveno vorbei, bis nach Ponte di Arche. Von dort führt der letzte Anstieg dieser Transalp, weiterhin auf der SS241 auf 740m. Abschließend geht es weiter bergab in Richtung Riva del Garda. Am Lago di Tenno verlässt ma die SS241 und wechselt auf die SP37 und folgt dieser bergab bis nach Riva. In Riva angekommen, nimmt man die SS240 bis zum Ortszentrum. Hier endet die letzte Etappe der Transalp und der Gardasee läd zu weiteren sportlichen Aktivitäten ein.",
      "Ausgangspunkt": "Cles",
      "Endpunkt": "Riva del Garda",
      "auf": 1626,
      "ab": 2107,
      "maxHoehe": 1044,
      "Schwierigkeitsgrad": "mittelschwierig",
      "Laenge": "75",
      "Zeit": "4",
      "Pässe": "Andalosattel, Passo del Ballino",
     
   },

}